export const LOAD_VALIDATION_RESULT = 'LOAD_VALIDATION_RESULT';
export const SHOW_MODAL_LOADER = 'SHOW_MODAL_LOADER';
export const LOAD_TOTAL_USERS_TO_EXTRACT = 'LOAD_TOTAL_USERS_TO_EXTRACT';
export const CURRENT_EXTRACT_COUNT = 'CURRENT_EXTRACT_COUNT';
export const RESET_LOADER_UI_STATE = 'RESET_LOADER_UI_STATE';