// @flow

export const LOAD_VALIDATION_RESULT: string = "LOAD_VALIDATION_RESULT";
export const SHOW_MODAL_LOADER: string = "SHOW_MODAL_LOADER";
export const LOAD_TOTAL_USERS_TO_EXTRACT: string =
  "LOAD_TOTAL_USERS_TO_EXTRACT";
export const INCREMENT_EXTRACT_COUNT: string = "INCREMENT_EXTRACT_COUNT";
export const RESET_LOADER_UI_STATE: string = "RESET_LOADER_UI_STATE";
export const LOAD_ALL_USERS_ACCESS: string = "LOAD_ALL_USERS_ACCESS";
export const IS_ERROR_OCCURED: string = "IS_ERROR_OCCURED";
export const SET_CANCEL_TOKEN: string = "SET_CANCEL_TOKEN";
export const SET_SHOW_MODAL_INFO: string = "SET_SHOW_MODAL_INFO";
