export const SET_GROUP_FILTERS = "SET_GROUP_FILTERS";
export const ADD_GROUPS_TO_EXISTING_COLLECTION_GROUP =
  "ADD_GROUPS_TO_EXISTING_COLLECTION_GROUP";
export const LOAD_LOCAL_STORAGE_FILTERS = "LOAD_LOCAL_STORAGE_FILTERS";
export const REARRANGE_GROUP_FILTERS = "REARRANGE_GROUP_FILTERS";
export const REARRANGE_GROUP_CHILD_FILTERS = "REARRANGE_GROUP_CHILD_FILTERS";
export const DELETE_GROUP_FILTER = "DELETE_GROUP_FILTER";
export const DELETE_GROUP_FILTER_CHILD = "DELETE_GROUP_FILTER_CHILD";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const UPDATE_FILTER_CHILD = "UPDATE_FILTER_CHILD";
