export const SET_GROUP_FILTERS = "SET_GROUP_FILTERS";
export const LOAD_LOCAL_STORAGE_FILTERS = "LOAD_LOCAL_STORAGE_FILTERS";
export const REARRANGE_GROUP_FILTERS = "REARRANGE_GROUP_FILTERS";
export const DELETE_GROUP_FILTER = "DELETE_GROUP_FILTER";
export const UPDATE_FILTER = "UPDATE_FILTER";
