export const VAL_SETUP_INPUT_HANDLER = "VAL_SETUP_INPUT_HANDLER";
export const HUB_REGION_INPUT_HANDLER = "HUB_REGION_INPUT_HANDLER";
export const SET_IS_VALIDATING_STATUS = "SET_IS_VALIDATING_STATUS";
export const TRIGGER_ERROR_ON_GROUP_NAME = "TRIGGER_ERROR_ON_GROUP_NAME";
export const TOGGLE_FORM_MODAL = "TOGGLE_FORM_MODAL";
export const RESET_FORM_MODAL = "RESET_FORM_MODAL";
export const RESET_FORM_MODAL_FIELD = "RESET_FORM_MODAL_FIELD";
