export const SET_GROUP_ALIAS = "SET_GROUP_ALIAS";
export const SET_GROUP_NAME = "SET_GROUP_NAME";
export const SET_HUB_REGION = "SET_HUB_REGION";
export const TRIGGER_ERROR_ON_GROUP_NAME = "TRIGGER_ERROR_ON_GROUP_NAME";
